"""Postman collection + pytest file export for API-target cases (PRD §7.6.2 step 6)."""

import json
import uuid

from app.services.execution.api_models import RequestPlan


def _plan_from_case(request_plan: dict[str, object]) -> RequestPlan:
    return RequestPlan.model_validate(request_plan)


def build_postman_collection(
    *, collection_name: str, base_url: str, cases: list[tuple[str, dict[str, object]]]
) -> dict[str, object]:
    """`cases` is (scenario_name, request_plan_dict) pairs, in suite order."""
    items = []
    for scenario, request_plan in cases:
        plan = _plan_from_case(request_plan)
        items.append(
            {
                "name": scenario,
                "request": {
                    "method": plan.method,
                    "header": [{"key": k, "value": v} for k, v in plan.headers.items()],
                    "url": {
                        "raw": base_url.rstrip("/") + plan.path,
                        "host": [base_url.rstrip("/")],
                        "path": [p for p in plan.path.split("/") if p],
                        "query": [{"key": k, "value": v} for k, v in plan.query.items()],
                    },
                    **(
                        {"body": {"mode": "raw", "raw": json.dumps(plan.body)}}
                        if plan.body is not None
                        else {}
                    ),
                },
            }
        )
    return {
        "info": {
            "name": collection_name,
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            "_postman_id": str(uuid.uuid4()),
        },
        "item": items,
    }


def build_pytest_file(*, base_url: str, cases: list[tuple[str, str, dict[str, object]]]) -> str:
    """`cases` is (display_id, scenario_name, request_plan_dict) triples, in suite order."""
    lines = [
        '"""Generated by QA Forge from an executed API suite — reproduces the request plans',
        "as plain httpx calls. Chained `{{var}}` placeholders are not re-resolved here; each",
        "test is independent and uses the literal values captured at generation time.",
        '"""',
        "",
        "import httpx",
        "import pytest",
        "",
        f'BASE_URL = "{base_url}"',
        "",
        "",
    ]
    for display_id, scenario, request_plan in cases:
        plan = _plan_from_case(request_plan)
        fn_name = (
            "test_" + "".join(c if c.isalnum() else "_" for c in f"{display_id}_{scenario}").lower()
        )
        fn_name = fn_name[:200]
        lines.append(f"def {fn_name}():")
        lines.append(f"    # {scenario}")
        kwargs = [f'"{plan.method}"', f'BASE_URL + "{plan.path}"']
        call_parts = [f"    response = httpx.request({', '.join(kwargs)}"]
        if plan.headers:
            call_parts.append(f", headers={plan.headers!r}")
        if plan.query:
            call_parts.append(f", params={plan.query!r}")
        if plan.body is not None:
            call_parts.append(f", json={plan.body!r}")
        call_parts.append(")")
        lines.append("".join(call_parts))
        for assertion in plan.assertions:
            if assertion.kind == "status_equals":
                lines.append(f"    assert response.status_code == {assertion.expected!r}")
            elif assertion.kind == "header_present":
                lines.append(f"    assert {assertion.path!r} in response.headers")
        lines.append("")
        lines.append("")
    return "\n".join(lines)
