"""phase5_secrets_test_runs_run_steps

Revision ID: eb20d40afde0
Revises: 94d27965446e
Create Date: 2026-10-01 15:56:33.301500
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "eb20d40afde0"
down_revision: str | None = "94d27965446e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite can't ALTER TABLE ADD FOREIGN KEY — adding `test_cases.last_run_id`'s FK forces
    # Alembic's batch mode to recreate the table (DROP + rename), which SQLite refuses under
    # FK enforcement while `evidence`/`bugs` already hold live FKs into test_cases.id. The app
    # turns FK enforcement on per-connection (`app/db/session.py`); toggling it off for the
    # duration of this migration is the standard workaround (must run outside a transaction,
    # which is why `alembic/env.py` runs SQLite migrations non-transactionally).
    op.execute("PRAGMA foreign_keys=OFF")

    op.create_table(
        "secrets",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("ciphertext", sa.String(length=2000), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "PASSWORD",
                "TOKEN",
                "API_KEY",
                "OAUTH_CLIENT",
                name="secretkind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_secrets_owner_id_users")),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_secrets_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secrets")),
        sa.UniqueConstraint("project_id", "name", name="uq_secrets_project_id_name"),
    )
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_secrets_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_secrets_project_id"), ["project_id"], unique=False)

    op.create_table(
        "test_runs",
        sa.Column("suite_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target",
            sa.Enum("WEB", "API", "ANDROID", name="runtarget", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "PASSED",
                "FAILED",
                "ERROR",
                "CANCELLED",
                name="runstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "config_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("guidance_text", sa.String(length=4000), nullable=False),
        sa.Column(
            "selected_case_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "summary_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_test_runs_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"], ["test_suites.id"], name=op.f("fk_test_runs_suite_id_test_suites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_runs")),
    )
    with op.batch_alter_table("test_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_runs_project_id"), ["project_id"], unique=False)

    # test_cases and evidence are altered (SQLite batch mode recreates the table) BEFORE
    # run_steps is created — run_steps has FKs to both, and SQLite's batch recreate of a
    # table fails with a FOREIGN KEY integrity error if another table already references it
    # (the drop-and-rename step can't proceed with a live incoming FK).
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tags",
                sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=False,
                server_default="[]",
            )
        )
        batch_op.add_column(sa.Column("last_run_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "automation_script",
                sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_test_cases_last_run_id_test_runs"), "test_runs", ["last_run_id"], ["id"]
        )

    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_evidence_run_id_test_runs"), "test_runs", ["run_id"], ["id"]
        )

    op.create_table(
        "run_steps",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("test_case_id", sa.Uuid(), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target", sa.String(length=500), nullable=True),
        sa.Column("input_masked", sa.String(length=1000), nullable=True),
        sa.Column("assertion", sa.String(length=500), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "PASS", "FAIL", "SKIP", "ERROR", name="runstepoutcome", native_enum=False, length=10
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=2000), nullable=True),
        sa.Column("screenshot_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["test_runs.id"], name=op.f("fk_run_steps_run_id_test_runs")
        ),
        sa.ForeignKeyConstraint(
            ["screenshot_evidence_id"],
            ["evidence.id"],
            name=op.f("fk_run_steps_screenshot_evidence_id_evidence"),
        ),
        sa.ForeignKeyConstraint(
            ["test_case_id"], ["test_cases.id"], name=op.f("fk_run_steps_test_case_id_test_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_steps")),
    )
    with op.batch_alter_table("run_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_steps_run_id"), ["run_id"], unique=False)

    op.execute("PRAGMA foreign_keys=ON")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### (reordered: run_steps,
    # which has live FKs into test_cases/evidence, must be dropped before those tables are
    # batch-recreated — see the matching note in upgrade())
    op.execute("PRAGMA foreign_keys=OFF")

    with op.batch_alter_table("run_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_steps_run_id"))

    op.drop_table("run_steps")

    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_evidence_run_id_test_runs"), type_="foreignkey")

    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_test_cases_last_run_id_test_runs"), type_="foreignkey"
        )
        batch_op.drop_column("automation_script")
        batch_op.drop_column("last_run_id")
        batch_op.drop_column("tags")

    with op.batch_alter_table("test_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_runs_project_id"))

    op.drop_table("test_runs")
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_secrets_project_id"))
        batch_op.drop_index(batch_op.f("ix_secrets_owner_id"))

    op.drop_table("secrets")
    op.execute("PRAGMA foreign_keys=ON")
    # ### end Alembic commands ###
