"""phase4 evidence bugs reports report_defaults note_snippets

Revision ID: 94d27965446e
Revises: e4c8155a3e50
Create Date: 2026-10-01 10:50:26.410504
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "94d27965446e"
down_revision: str | None = "e4c8155a3e50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note_snippets",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note_snippets")),
    )
    op.create_table(
        "report_defaults",
        sa.Column(
            "exit_criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "approval_roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("classification_label", sa.String(length=50), nullable=False),
        sa.Column("organisation_name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_defaults")),
    )
    op.create_table(
        "reports",
        sa.Column("suite_id", sa.Uuid(), nullable=False),
        sa.Column("template_docx_id", sa.Uuid(), nullable=True),
        sa.Column(
            "fields_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("file_key", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["users.id"], name=op.f("fk_reports_generated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"], ["test_suites.id"], name=op.f("fk_reports_suite_id_test_suites")
        ),
        sa.ForeignKeyConstraint(
            ["template_docx_id"],
            ["templates.id"],
            name=op.f("fk_reports_template_docx_id_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_suite_id"), ["suite_id"], unique=False)

    op.create_table(
        "bugs",
        sa.Column("suite_id", sa.Uuid(), nullable=False),
        sa.Column("test_case_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "CRITICAL", "HIGH", "MEDIUM", "LOW", name="severity", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "FIXED",
                "RETESTED",
                "CLOSED",
                name="bugstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("external_link", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["suite_id"], ["test_suites.id"], name=op.f("fk_bugs_suite_id_test_suites")
        ),
        sa.ForeignKeyConstraint(
            ["test_case_id"], ["test_cases.id"], name=op.f("fk_bugs_test_case_id_test_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bugs")),
    )
    with op.batch_alter_table("bugs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bugs_suite_id"), ["suite_id"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("test_case_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "SCREENSHOT",
                "REQUEST_LOG",
                "VIDEO",
                "FILE",
                name="evidencekind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("file_key", sa.String(length=500), nullable=False),
        sa.Column("caption", sa.String(length=300), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_case_id"], ["test_cases.id"], name=op.f("fk_evidence_test_case_id_test_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_test_case_id"), ["test_case_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_test_case_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("bugs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bugs_suite_id"))

    op.drop_table("bugs")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_suite_id"))

    op.drop_table("reports")
    op.drop_table("report_defaults")
    op.drop_table("note_snippets")
    # ### end Alembic commands ###
