"""phase2 templates

Revision ID: ab3e8a0f98a9
Revises: a42d6492295d
Create Date: 2026-10-01 00:19:03.325720
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ab3e8a0f98a9"
down_revision: str | None = "a42d6492295d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column(
            "kind",
            sa.Enum(
                "XLSX_TEST_CASES", "DOCX_REPORT", name="templatekind", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("file_key", sa.String(length=500), nullable=False),
        sa.Column("rendered_key", sa.String(length=500), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("type_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "ACTIVE", "ARCHIVED", name="templatestatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("validation_error", sa.String(length=2000), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"], ["test_case_types.id"], name=op.f("fk_templates_type_id_test_case_types")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_templates_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("templates")
    # ### end Alembic commands ###
