"""phase6_api_request_plan

Revision ID: 4ff5a7ca074d
Revises: eb20d40afde0
Create Date: 2026-10-01 16:50:19.983751
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4ff5a7ca074d"
down_revision: str | None = "eb20d40afde0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "request_plan",
                sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.drop_column("request_plan")

    # ### end Alembic commands ###
