"""phase7_android_apks

Revision ID: a6c905e9c5bd
Revises: 4ff5a7ca074d
Create Date: 2026-10-01 22:46:38.363137
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a6c905e9c5bd"
down_revision: str | None = "4ff5a7ca074d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apks",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("file_key", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=300), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("package_name", sa.String(length=300), nullable=False),
        sa.Column("launch_activity", sa.String(length=300), nullable=False),
        sa.Column("version_name", sa.String(length=100), nullable=False),
        sa.Column("version_code", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_apks_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_apks_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apks")),
    )
    with op.batch_alter_table("apks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_apks_project_id"), ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("apks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apks_project_id"))

    op.drop_table("apks")
    # ### end Alembic commands ###
