"""phase8_usage_records

Revision ID: 142105968521
Revises: a6c905e9c5bd
Create Date: 2026-10-01 23:36:09.394479
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "142105968521"
down_revision: str | None = "a6c905e9c5bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_records",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("feature", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_usage_records_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usage_records_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_records_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_records_feature"), ["feature"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_records_feature"))
        batch_op.drop_index(batch_op.f("ix_usage_records_at"))
        batch_op.drop_index(batch_op.f("ix_usage_records_actor_id"))

    op.drop_table("usage_records")
    # ### end Alembic commands ###
