"""phase3 projects stories suites cases generation_jobs

Revision ID: e4c8155a3e50
Revises: ab3e8a0f98a9
Create Date: 2026-10-01 00:33:25.624701
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e4c8155a3e50"
down_revision: str | None = "ab3e8a0f98a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("app_code", sa.String(length=50), nullable=False),
        sa.Column("id_prefix", sa.String(length=50), nullable=False),
        sa.Column("user_group_dept", sa.String(length=200), nullable=True),
        sa.Column("solution_provider", sa.String(length=200), nullable=True),
        sa.Column(
            "developers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=200), nullable=True),
        sa.Column("default_test_url", sa.String(length=500), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "members",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "approvers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "test_suites",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("type_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "IN_REVIEW", "FINAL", name="suitestatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "story_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "header_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "default_version_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("template_xlsx_id", sa.Uuid(), nullable=True),
        sa.Column("template_docx_id", sa.Uuid(), nullable=True),
        sa.Column("test_cycle", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_test_suites_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["template_docx_id"],
            ["templates.id"],
            name=op.f("fk_test_suites_template_docx_id_templates"),
        ),
        sa.ForeignKeyConstraint(
            ["template_xlsx_id"],
            ["templates.id"],
            name=op.f("fk_test_suites_template_xlsx_id_templates"),
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["test_case_types.id"], name=op.f("fk_test_suites_type_id_test_case_types")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_suites")),
    )
    with op.batch_alter_table("test_suites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_suites_project_id"), ["project_id"], unique=False)

    op.create_table(
        "user_stories",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "source",
            sa.Enum("UPLOAD", "PASTE", "URL", name="storysource", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("file_key", sa.String(length=500), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column(
            "acceptance_criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "analysis_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_user_stories_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_user_stories_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_stories")),
    )
    with op.batch_alter_table("user_stories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_stories_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "generation_jobs",
        sa.Column("suite_id", sa.Uuid(), nullable=False),
        sa.Column(
            "story_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                name="generationjobstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_estimate", sa.Double(), nullable=False),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["suite_id"], ["test_suites.id"], name=op.f("fk_generation_jobs_suite_id_test_suites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_jobs")),
    )
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_generation_jobs_suite_id"), ["suite_id"], unique=False)

    op.create_table(
        "test_cases",
        sa.Column("suite_id", sa.Uuid(), nullable=False),
        sa.Column(
            "section",
            sa.Enum("DEFAULT", "FUNCTIONAL", name="casesection", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("case_no", sa.Integer(), nullable=False),
        sa.Column("display_id", sa.String(length=50), nullable=False),
        sa.Column("feature", sa.String(length=300), nullable=False),
        sa.Column("scenario", sa.String(length=2000), nullable=False),
        sa.Column(
            "steps",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expected_result", sa.String(length=2000), nullable=False),
        sa.Column("actual_result", sa.String(length=2000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PASSED",
                "FAILED",
                "NOT_TESTED",
                "SUSPENDED",
                "MODIFICATION",
                "BLOCKED",
                name="teststatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_regression", sa.Boolean(), nullable=False),
        sa.Column("evidence_group", sa.String(length=100), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("P1", "P2", "P3", "P4", name="priority", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "technique",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "traces_to",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "DEFAULT", "AI", "MANUAL", "RUN", name="casesource", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("default_case_id", sa.Uuid(), nullable=True),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column(
            "execution_mode",
            sa.Enum("MANUAL", "AUTOMATED", name="executionmode", native_enum=False, length=20),
            nullable=True,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_case_id"],
            ["default_test_cases.id"],
            name=op.f("fk_test_cases_default_case_id_default_test_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"], ["test_suites.id"], name=op.f("fk_test_cases_suite_id_test_suites")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_cases")),
    )
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_cases_suite_id"), ["suite_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_cases_suite_id"))

    op.drop_table("test_cases")
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_jobs_suite_id"))

    op.drop_table("generation_jobs")
    with op.batch_alter_table("user_stories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_stories_project_id"))

    op.drop_table("user_stories")
    with op.batch_alter_table("test_suites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_suites_project_id"))

    op.drop_table("test_suites")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_owner_id"))

    op.drop_table("projects")
    # ### end Alembic commands ###
