"""feature_flags

Revision ID: b2230f9f3a83
Revises: 142105968521
Create Date: 2026-10-06 11:09:53.551759
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b2230f9f3a83"
down_revision: str | None = "142105968521"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_feature_flags_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_feature_flags")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
